/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWsNewRouteImport } from './routes/_authenticated/ws.new'
import { Route as AuthenticatedWsWorkspaceIdHomeRouteImport } from './routes/_authenticated/ws.$workspaceId.home'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWsNewRoute = AuthenticatedWsNewRouteImport.update({
  id: '/ws/new',
  path: '/ws/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWsWorkspaceIdHomeRoute =
  AuthenticatedWsWorkspaceIdHomeRouteImport.update({
    id: '/ws/$workspaceId/home',
    path: '/ws/$workspaceId/home',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/ws/new': typeof AuthenticatedWsNewRoute
  '/ws/$workspaceId/home': typeof AuthenticatedWsWorkspaceIdHomeRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/ws/new': typeof AuthenticatedWsNewRoute
  '/ws/$workspaceId/home': typeof AuthenticatedWsWorkspaceIdHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ws/new': typeof AuthenticatedWsNewRoute
  '/_authenticated/ws/$workspaceId/home': typeof AuthenticatedWsWorkspaceIdHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/ws/new' | '/ws/$workspaceId/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/ws/new' | '/ws/$workspaceId/home'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/ws/new'
    | '/_authenticated/ws/$workspaceId/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ws/new': {
      id: '/_authenticated/ws/new'
      path: '/ws/new'
      fullPath: '/ws/new'
      preLoaderRoute: typeof AuthenticatedWsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ws/$workspaceId/home': {
      id: '/_authenticated/ws/$workspaceId/home'
      path: '/ws/$workspaceId/home'
      fullPath: '/ws/$workspaceId/home'
      preLoaderRoute: typeof AuthenticatedWsWorkspaceIdHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedWsNewRoute: typeof AuthenticatedWsNewRoute
  AuthenticatedWsWorkspaceIdHomeRoute: typeof AuthenticatedWsWorkspaceIdHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedWsNewRoute: AuthenticatedWsNewRoute,
  AuthenticatedWsWorkspaceIdHomeRoute: AuthenticatedWsWorkspaceIdHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
